name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '20 21 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
                # Number of days of inactivity before an issue becomes stale
        daysUntilStale: 60
        # Number of days of inactivity before a stale issue is closed
        daysUntilClose: 7
        # Issues with these labels will never be considered stale
        
        # Label to use when marking an issue as stale
        staleLabel: wontfix
        # Comment to post when marking an issue as stale. Set to `false` to disable
        markComment: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        # Comment to post when closing a stale issue. Set to `false` to disable
        closeComment: false
